### PR TITLE
Crear endpoints CRUD para el formulario de gestión de Volumenes #7

### LINKED ISSUE #7: Crear endpoints CRUD para el formulario de gestión de Volumenes
**Descripción**
Desarrollar los endpoints GET, POST, PUT (update), DELETE y GET
para gestionar la creación, consulta, actualización y eliminación de volumenes en base al formulario proporcionado. Estos endpoints serán parte de la API y se conectarán con la base de datos para realizar las operaciones necesarias.

**Detalles del formulario**

Title: Texto, obligatorio
Date: Fecha, obligatorio
Article: Desplegable, selección de opciones predefinidas. Article será tratado como una colección separada, lo que implica una relación entre las colecciones.
Year_Volume: Desplegable, selección de opciones predefinidas
Portrait: Imagen, obligatorio

**Endpoints a desarrollar:**

GET /volume - Lista todos los artículos.
POST /volume  - Crea un nuevo artículo.
PUT /volume /{id} - Actualiza un artículo existente.
DELETE /volume /{id} - Elimina un artículo.
GET /volume /{id} - Consulta los detalles de un artículo específico.
**Criterios de aceptación**

- Cada endpoint debe validar la entrada de datos según los requisitos del formulario.
- Manejar errores y devolver respuestas apropiadas (ej. 400 para datos incorrectos, 404 para no encontrado).
- Asegurar la seguridad en el manejo de la carga de imágenes.
- Documentación de la API actualizada incluyendo estos endpoints.

### PR DESCRIPTION
**Pull request by SergioA1228**

### CODE REVIEW

**Review by Ditmar — CHANGES_REQUESTED** [review]
refactor the code bases in the implementation of luis

**Comment by SergioA1228** [comment]
There is no need to refactor the code anymore, Luis implemented a fix in his code in media-routers.ts

**Review by Ditmar — APPROVED** [review]

**Pull request merged**
